name: Fix Marquee IMG v1.2
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - '.github/workflows/marquee.yaml'  # Triggers on changes to this file

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find and update <img> tags within <marquee>
        run: |
          find . -name '*.html' | while read file; do
            if grep -q '<marquee>' "$file"; then
              # Backup the original file
              cp "$file" "$file.bak"
              
              # Use sed to modify the style attribute of <img> tags within <marquee> tags
              sed -i '/<marquee>/,/<\/marquee>/ {
                /<img/s/style="/style="display: inline-block; height: 80px; margin-right: 20px; vertical-align: middle; /
              }' "$file"
              
              # Check if the file was modified and report changes
              if ! diff "$file" "$file.bak" &> /dev/null; then
                echo "Updated $file"
              fi
              # Clean up the backup file
              rm "$file.bak"
            fi
          done
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet; then
            git add .
            git commit -m "Update <img> tags within <marquee> in HTML files"
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
