name: Fix Marquee IMG v4
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - '.github/workflows/fix-marquee-img.yml'  # Triggers on changes to this file

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Find and update <img> tags within <marquee>
        id: update_html
        run: |
          import os
          from bs4 import BeautifulSoup

          def process_file(file_path):
              with open(file_path, 'r', encoding='utf-8') as file:
                  content = file.read()
              
              soup = BeautifulSoup(content, 'html.parser')
              marquees = soup.find_all('marquee')
              
              if not marquees:
                  return False
              
              changed = False
              for marquee in marquees:
                  imgs = marquee.find_all('img')
                  for img in imgs:
                      current_style = img.get('style', '')
                      new_style = f"{current_style} display: inline-block; height: 80px; margin-right: 20px; vertical-align: middle;".strip()
                      img['style'] = new_style
                      changed = True
              
              if changed:
                  with open(file_path, 'w', encoding='utf-8') as file:
                      file.write(str(soup))
                  print(f"Updated {file_path}")
              
              return changed

          changed_files = []
          for root, dirs, files in os.walk('.'):
              for file in files:
                  if file.endswith('.html'):
                      file_path = os.path.join(root, file)
                      if process_file(file_path):
                          changed_files.append(file_path)

          if changed_files:
              print("Files changed:")
              for file in changed_files:
                  print(file)
              print("::set-output name=changed::true")
          else:
              print("No changes made.")
              print("::set-output name=changed::false")
        shell: python

      - name: Commit and push changes
        if: steps.update_html.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update <img> tags within <marquee> in HTML files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
